apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
        - name: cards
          image: cards/prueba
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: cards
spec:
  selector:
    app: cards
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer